# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./sc-epgp-ui
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: npm ci
      run: npm ci
    - name: npm build
      run: npm run build --if-present
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.DROPLET_USER }}
        server: ${{ secrets.DROPLET_HOST }}
        port: 22
        ssh_private_key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        local_path: ./dist
        remote_path: ${{ secrets.DROPLET_TARGET_DIR }}
